# Generated by Django 4.1.5 on 2023-01-25 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Date when the object was added')),
                ('modified', models.DateField(auto_now=True, verbose_name='Data for the last edition')),
                ('active', models.BooleanField(default=True, verbose_name='Is active the record?(logical deletion)')),
                ('name', models.CharField(max_length=100, verbose_name='Company name')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Date when the object was added')),
                ('modified', models.DateField(auto_now=True, verbose_name='Data for the last edition')),
                ('active', models.BooleanField(default=True, verbose_name='Is active the record?(logical deletion)')),
                ('first_name', models.CharField(max_length=100, verbose_name='Customer first name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Customer last name')),
                ('email', models.EmailField(max_length=254, verbose_name='Customer email')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Date when the object was added')),
                ('modified', models.DateField(auto_now=True, verbose_name='Data for the last edition')),
                ('active', models.BooleanField(default=True, verbose_name='Is active the record?(logical deletion)')),
                ('name', models.CharField(max_length=100, verbose_name='Room name')),
                ('capacity', models.SmallIntegerField(verbose_name='Max capacity for the room')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='events_manager.company')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Date when the object was added')),
                ('modified', models.DateField(auto_now=True, verbose_name='Data for the last edition')),
                ('active', models.BooleanField(default=True, verbose_name='Is active the record?(logical deletion)')),
                ('name', models.CharField(max_length=100, verbose_name='Event name')),
                ('date', models.DateField(verbose_name='Event date')),
                ('public', models.BooleanField(default=True, verbose_name='Is a public event?')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='events_manager.company')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='events_manager.room')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Date when the object was added')),
                ('modified', models.DateField(auto_now=True, verbose_name='Data for the last edition')),
                ('active', models.BooleanField(default=True, verbose_name='Is active the record?(logical deletion)')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='events_manager.customer')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='events_manager.event')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
            },
        ),
    ]
